# Generated by Django 4.1.2 on 2022-11-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя/организации')),
                ('mail', models.CharField(max_length=100, verbose_name='Почта пользователя/организации')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('devices', models.CharField(max_length=100, verbose_name='Название прибора')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
